// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using InspirationalQuotes.Data.DBContext;

#nullable disable

namespace inspirational_quotes_Backend.Migrations
{
    [DbContext(typeof(QuoteDBContext))]
    [Migration("20240411102437_QuoteTable")]
    partial class QuoteTable
    {
        /// <inheritdoc />
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

//            modelBuilder.Entity("inspirational_quotes_Backend.Models.Quote", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("INTEGER");

//                    b.Property<string>("Author")
//                        .IsRequired()
//                        .HasColumnType("TEXT");

//                    b.Property<string>("QuoteDesp")
//                        .IsRequired()
//                        .HasColumnType("TEXT");

//                    b.Property<string>("Tags")
//                        .IsRequired()
//                        .HasColumnType("TEXT");

//                    b.HasKey("Id");

//                    b.ToTable("Quotes");
//                });
//#pragma warning restore 612, 618
//        }
    }
}
